apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: twitterlive-hpa
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: twitterlive
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 25
  - type: Pods
    pods:
      metricName: packets-per-second
      targetAverageValue: 100
  - type: Object
    object:
      target:
        kind: Service
        name: webfront
      metricName: http_request
      # metricName: net.http.request.count
      targetValue: 50